---
 - name: Install the PHP5 Repository 
   apt_repository:
     repo: 'ppa:ondrej/php5'
     state: present
 
 - name: Update the Repositories 
   apt:
     update_cache: yes
 
 - name: Install PHP5-FPM
   apt:
     name: "{{ item }}"
     state: latest
   with_items:
     - php5-fpm
     - php5-cgi
     - php5-cli
     - php5-curl
     - php5-json
     - php5-odbc
     - php5-tidy
     - php5-common
     - php5-xmlrpc
     - php5-gd
     - php-pear
     - php5-dev
     - php5-imap
     - php5-mcrypt
     - php5-mysqlnd

 - name: Copy custom www.conf file with the Change in permission of php5-fpm.sock
   copy:
     src: www.conf
     dest: /etc/php5/fpm/pool.d
     owner: root
     group: root
     backup: yes
   notify:
     - Restart PHP5-FPM

 - name: Copy custom php.ini file(cgi.fix_pathinfo=0) 
   copy:
     src: php.ini
     dest: /etc/php5/fpm
     owner: root
     group: root
     backup: yes
   notify:
     - Restart PHP5-FPM 
